### ISSUE TITLE
java파일에서 직접 setter로 값을 대입하는 column은

### ISSUE THREAD

**Issue by new-coding-study** [ssssong125/Apollo#110]
혹은 한 테이블의 모든 필드 변수 값을 setter로 대입 한다면
query문을 쓸 필요가 없을까요?

보통은 setter를 쓰지 않고 값을 html에서 받아서 그냥 쓰니까

**Comment by ssssong125** [comment]
쿼리문은 db에서 값을 받아와서 필요하고 세터를 안쓰면 dto객체에 해당 필드값을 못채워서 아예 새로운 객체를 만든다면 상관없을거같아요
